#!/usr/bin/env python
"""Engineering lineages: which entries are variants of which other entries.

One row per deposited variant, grouped under the wild-type entries it derives
from.  Everything is read from Scientific_data/provenance/engineering_lineages.tsv,
which is itself generated by build_lineage_tables.py, so the table cannot drift
from the substitutions and affinities that were actually computed.
"""
from pathlib import Path
import csv, collections

from figstyle import *          # canvas, type scale, ink, save

# The tables keep the pre-2026-09 type scale.  The figures were enlarged because
# they are reduced on placement; these tables are placed at their drawn width,
# and every column here is measured in mm against text set at 7 pt.
FS_BODY, FS_SMALL, FS_HEAD = 7.0, 6.5, 7.0
F_BODY, F_SMALL, F_HEAD = font(FS_BODY), font(FS_SMALL), font(FS_HEAD, bold=True)

PROV = Path(__file__).resolve().parents[2] / "Scientific_data" / "provenance"
SRC = PROV / "engineering_lineages.tsv"

# fully achromatic, like Table 1: the grouping is carried by rules, indentation
# and weight.  Hue in this manuscript encodes data, and nothing here is data.
F_NAME, F_ID = F_BODY, font(FS_SMALL, mono=True)
F_SUB = F_BODY

# column geometry, in mm from the left text edge
IND = 3.6                       # variant rows sit inside the lineage band
X_PDB, X_N, X_SUB = 30.0, 46.0, 49.0
X_KD, X_RATIO = 124.0, W        # right edges
LH, GAP_BAND, PAD_BAND = 3.55, 3.2, 1.4

GREEK = {"alpha": "α", "beta": "β"}
STRIP = "( -_"                  # a lineage name is followed by one of these
EXPLICIT = 3                    # up to this many substitutions are spelled out


def short(lineage, name):
    """'DMF5 aD26Y/bL98W' -> 'aD26Y/bL98W'; the lineage heads the block already.

    Only a lineage name followed by a separator is stripped, so A6c134 and
    JDIa41b1 keep theirs: there the lineage name is part of the published name
    rather than a prefix on it.
    """
    if name.startswith(lineage) and name[len(lineage):len(lineage) + 1] in STRIP:
        return name[len(lineage):].strip(STRIP + ")")
    return name


def loops(regions):
    """'CDR1-alpha,FR2-beta,CDR3-beta' -> 'α1 β3 +FR'.

    The chain comes first because that is how a reader groups them, and the
    numbers are bare because the column is headed CDR loops.
    """
    seen, fr = [], False
    for r in regions.split(","):
        if not r:
            continue
        name, _, chain = r.partition("-")
        if name.startswith("FR"):
            fr = True
            continue
        tag = GREEK.get(chain, chain) + name[3:]
        if tag not in seen:
            seen.append(tag)
    return " ".join(seen) + (" +FR" if fr else "")


def changes(r):
    """The wide cell: the substitutions themselves when few, the loops when many."""
    if int(r["n_substitutions"]) <= EXPLICIT:
        return " · ".join(f"{GREEK[c]} {s}"
                          for c, k in (("alpha", "substitutions_alpha"),
                                       ("beta", "substitutions_beta"))
                          for s in (r[k].split(",") if r[k] else []))
    return loops(r["imgt_regions"])


def ratio(x):
    if not x:
        return ""
    v = float(x)
    return f"{v:,.0f}×" if v >= 100 else (f"{v:.1f}×" if v >= 1
                                               else f"{v:.2g}×")


def load():
    rows = list(csv.DictReader(open(SRC, encoding="utf-8"), delimiter="\t"))
    lin = collections.OrderedDict()
    for r in rows:
        lin.setdefault(r["lineage"], {"parent": [], "derived": []})
        lin[r["lineage"]]["parent" if r["role"] == "parent"
                          else "derived"].append(r)
    return rows, lin


LEGEND = {   # prose harvested by build_legends.py; see figstyle.LEAN
    "title": "Engineering lineages inside the library",
    "subtitle": "Thirteen receptors are present both as a wild-type entry and as one or more "
                "deposited variants of themselves. Each variant is placed against the "
                "wild-type entry it differs from least.",
    "notes": [],
}


def draw(ax, top, w):
    rows, lin = load()
    nd = sum(1 for r in rows if r["role"] == "derivative")
    npair = sum(1 for r in rows if r["kd_fold_change"])
    cross = sorted({r["pdb_id"] for r in rows
                    if "different studies" in r["kd_fold_flag"]})

    LEGEND["notes"] = [
        f"{len(rows)} entries in {len(lin)} lineages: {len(rows) - nd} wild-type and {nd} "
        "variants. Substitutions are counted by numbering both chains with ANARCI in the "
        "IMGT scheme and comparing them position by position over the variable domain, so "
        "they are independent of how the depositors named their mutants; a substitution is "
        "written as the wild-type residue, the IMGT position, and the variant residue, with "
        "an insertion-coded position such as 112A written out in full. IMGT positions 1 and "
        "2 are excluded because deposited constructs disagree there over cloning remnants. "
        "n counts substitutions anywhere in the variable domain; the loops are named by "
        "chain and CDR number, and +FR marks a variant that also differs in the framework.",
        "The comparison is against the closest wild-type entry of the same lineage, which is "
        "named in engineering_lineages.tsv together with the full substitution list, the "
        "peptide, the allele and the source publication of every value here.",
        "Dissociation constants are surface-plasmon-resonance values from IEDB. A parent and "
        "a variant are only paired when both were measured against the same peptide and the "
        f"same allele, which is possible for {npair} of the {nd} variants; the ratio is the "
        "parent constant divided by the variant constant, so a ratio above one means the "
        "variant binds more tightly. Ratios above one thousand rest on a variant value at "
        "the resolution limit of the source column, which stores this field as an integer "
        "in nanomolar, and are lower bounds rather than measurements. Where parent and "
        "variant come from different publications the ratio also carries their "
        f"between-laboratory spread ({', '.join(cross)}).",
        "The TK3 variants are the counter-example the others need: two single substitutions "
        "at one framework position adjoining CDR2 of the beta chain that both weaken "
        "binding, one of them sixteen-fold. Affinity maturation is the common reason to "
        "engineer a receptor, not the only one.",
    ]

    y = header(ax, 0, top, w, LEGEND["title"], LEGEND["subtitle"])
    y -= 3.6

    for x, t, ha in ((0.0, "Variant", "left"), (X_PDB, "PDB", "left"),
                     (X_N, "n", "right"),
                     (X_SUB, "Substitutions or loops", "left"),
                     (X_KD, "KD (nM), parent → variant", "right"),
                     (X_RATIO, "ratio", "right")):
        ax.text(x, y, t, fontproperties=F_HEAD, color=INK, ha=ha, va="baseline")
    y -= 1.6
    rule(ax, 0, w, y, lw=0.9)
    y -= LH

    for name, grp in lin.items():
        y -= GAP_BAND
        ax.text(0, y, name, fontproperties=font(FS_BODY, bold=True), color=INK,
                ha="left", va="baseline")
        wt = " ".join(r["pdb_id"] for r in grp["parent"])
        ax.text(X_PDB, y, wt, fontproperties=F_ID, color=SECONDARY,
                ha="left", va="baseline")
        ax.text(X_RATIO, y, f"wild type, {len(grp['parent'])} "
                            f"{'entries' if len(grp['parent']) > 1 else 'entry'}",
                fontproperties=F_BODY, color=SECONDARY, ha="right", va="baseline")
        y -= 1.3
        rule(ax, 0, w, y, lw=0.35, color=INK)
        y -= LH * 0.92

        for r in grp["derived"]:
            ax.text(IND, y, short(name, r["variant_name"]),
                    fontproperties=F_NAME, color=INK, ha="left", va="baseline")
            ax.text(X_PDB, y, r["pdb_id"], fontproperties=F_ID, color=INK,
                    ha="left", va="baseline")
            ax.text(X_N, y, r["n_substitutions"], fontproperties=F_BODY,
                    color=INK, ha="right", va="baseline")
            ax.text(X_SUB, y, changes(r), fontproperties=F_SUB, color=SECONDARY,
                    ha="left", va="baseline")
            if r["kd_parent_nm"]:
                ax.text(X_KD, y, f"{r['kd_parent_nm']} → {r['kd_nm']}",
                        fontproperties=F_BODY, color=INK, ha="right", va="baseline")
                ax.text(X_RATIO, y, ratio(r["kd_fold_change"]),
                        fontproperties=F_BODY, color=INK, ha="right", va="baseline")
            else:
                ax.text(X_RATIO, y, "—", fontproperties=F_BODY, color=MUTE,
                        ha="right", va="baseline")
            y -= LH

    y -= 1.0
    rule(ax, 0, w, y, lw=0.9)
    return notes(ax, 0, w, y - 1.2, LEGEND["notes"], gap=1.6, rule_lw=0.0)


if __name__ == "__main__":
    render(draw, "Table_lineage")
    rows, lin = load()
    lim = {"name": (X_PDB - IND, F_NAME), "subs": (X_KD - X_SUB - 4, F_SUB)}
    bad = [(r["pdb_id"], k, round(text_w(t, fp), 1), lo)
           for k, g in lin.items() for r in g["derived"]
           for k2, t in (("name", short(k, r["variant_name"])), ("subs", changes(r)))
           for lo, fp in [lim[k2]] if text_w(t, fp) > lo]
    print("   column overflow:", bad or "none")
    wt = [(k, round(text_w(" ".join(r["pdb_id"] for r in g["parent"]), F_ID), 1))
          for k, g in lin.items()]
    print("   widest wild-type list:", max(wt, key=lambda x: x[1]))
